# Desafio Python e SQL

### Update

In [29]:
import pyodbc
from pathlib import Path
import pandas as pd

dados_conexao = (
    'driver={SQLite3 ODBC Driver};'
    'host=localhost;'
    fr'database={Path("./Dados/chinook.db")};'
)

In [30]:
conexao = pyodbc.connect(dados_conexao)
cursor = conexao.cursor()

try:
    cursor.execute('''
SELECT * FROM customers WHERE CustomerId = 1
''')
    clientes = cursor.fetchall()
    colunas = [col[0] for col in cursor.description]
    display(pd.DataFrame.from_records(clientes, columns=colunas))
finally:
    cursor.close()
    conexao.close()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3

In [33]:
try:
    conexao = pyodbc.connect(dados_conexao)
    cursor = conexao.cursor()
    cursor.execute('''
UPDATE customers SET FirstName = 'Anderson', Email = 'anderson.correa@outlook.com' WHERE CustomerId = 1
''')
    conexao.commit()
finally:
    cursor.close()
    conexao.close()

In [36]:
conexao = pyodbc.connect(dados_conexao)
cursor = conexao.cursor()

try:
    cursor.execute('''
SELECT * FROM customers WHERE CustomerId = 1
''')
    clientes = cursor.fetchall()
    colunas = [col[0] for col in cursor.description]
    display(pd.DataFrame.from_records(clientes, columns=colunas))
finally:
    cursor.close()
    conexao.close()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Anderson,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,anderson.correa@outlook.com,3